SELECT DISTINCT ?givenNameLabel ?familyNameLabel ?wdLabel ?wd ?article WHERE {
  ?wd wdt:P106 wd:Q17769800;
      wdt:P31 wd:Q5;
      wdt:P734 ?familyName;
      wdt:P735 ?givenName.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  OPTIONAL {
    ?article schema:about ?wd;
      schema:inLanguage "en";
      schema:isPartOf <https://en.wikipedia.org/>.
  }
}

